// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmdmxcTsU5SUzy--g7pnq47BMeO70dV7k',
    appId: '1:236689599750:web:adf4312d615da275c08287',
    messagingSenderId: '236689599750',
    projectId: 'campusconnecttemp',
    authDomain: 'campusconnecttemp.firebaseapp.com',
    storageBucket: 'campusconnecttemp.firebasestorage.app',
    measurementId: 'G-1T3V3MGCHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALE4aolAPw2B1eJRA-sxyO7CxKoWzTAs0',
    appId: '1:236689599750:android:ffdfcbd514a9c7b2c08287',
    messagingSenderId: '236689599750',
    projectId: 'campusconnecttemp',
    storageBucket: 'campusconnecttemp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZVK_H4tufkXytwsV1mOpnYdUV2UCtzw',
    appId: '1:236689599750:ios:c32af1b7449f5ba4c08287',
    messagingSenderId: '236689599750',
    projectId: 'campusconnecttemp',
    storageBucket: 'campusconnecttemp.firebasestorage.app',
    iosBundleId: 'com.example.campusConnectTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmdmxcTsU5SUzy--g7pnq47BMeO70dV7k',
    appId: '1:236689599750:web:6821828fddcb1bacc08287',
    messagingSenderId: '236689599750',
    projectId: 'campusconnecttemp',
    authDomain: 'campusconnecttemp.firebaseapp.com',
    storageBucket: 'campusconnecttemp.firebasestorage.app',
    measurementId: 'G-CL3THYV914',
  );
}
